apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "paidiver-annotations-api.fullname" . }}
  labels:
    {{- include "paidiver-annotations-api.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
      component: {{ .Values.api.component_name }}
      {{- include "paidiver-annotations-api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
        component: {{ .Values.api.component_name }}
        {{- include "paidiver-annotations-api.labels" . | nindent 8 }}
    spec:
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      initContainers:
        - name: wait-for-postgres
          image: bitnami/postgresql:latest
          command:
            - sh
            - -ec
            - |
              echo "Waiting for PostgreSQL..."
              until pg_isready \
                -h {{ printf "%s-postgresql" .Release.Name }} \
                -p 5432 \
                -U {{ .Values.postgresql.auth.username }}; do
                sleep 2
              done
          securityContext:
            runAsUser: 1000
            {{- toYaml .Values.containerSecurityContext | nindent 12 }}
      containers:
        - name: api
          image: "{{ .Values.api.image.repository }}:{{ .Values.api.image.tag }}"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{ .Values.api.port }}
          env:
            - name: POSTGRES_HOST
              value: {{ printf "%s-postgresql" .Release.Name }}
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_DB
              value: {{ .Values.postgresql.auth.database }}
            - name: POSTGRES_USER
              value: {{ .Values.postgresql.auth.username }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: annotations-api-db
                  key: password
            - name: DJANGO_SECRET_KEY
              value: dev-secret-key-change-me
            - name: DJANGO_DEBUG
              value: "1"
            - name: DJANGO_ALLOWED_HOSTS
              value: localhost,127.0.0.1,0.0.0.0
            - name: APP_ROOT_PATH
              value: {{ .Values.ingress.api.path }}
          command:
            - sh
            - -c
            - |
              python manage.py migrate &&
              poetry run gunicorn config.wsgi:application -w {{ .Values.api.workers }} -b 0.0.0.0:{{ .Values.api.port }} --timeout {{ .Values.api.timeout }}
          securityContext:
            runAsUser: 1000
            {{- toYaml .Values.containerSecurityContext | nindent 12 }}
      imagePullSecrets:
        - name: ghcr-pull-login
