apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-{{ .Values.api.componentName }}-service"
  labels:
    {{- include "paidiver-annotations-api.labels" . | nindent 4 }}
spec:
  selector:
    app: {{ .Release.Name }}
    component: {{ .Values.api.componentName }}
  ports:
    - port: {{ .Values.api.service.port }}
      targetPort: {{ .Values.api.port }}
