apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "paidiver-annotations-api.fullname" . }}
  labels:
    {{- include "paidiver-annotations-api.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  {{- if eq .Values.replicaCount 1.0}}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  {{- end }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
      component: {{ .Values.api.componentName }}
      {{- include "paidiver-annotations-api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
        component: {{ .Values.api.componentName }}
        {{- include "paidiver-annotations-api.labels" . | nindent 8 }}
    spec:
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      initContainers:
        - name: wait-for-postgres
          image: bitnami/postgresql:latest
          command:
            - sh
            - -ec
            - |
              echo "Waiting for PostgreSQL..."
              until pg_isready \
                -h {{ printf "%s-postgresql" .Release.Name }} \
                -p 5432 \
                -U {{ .Values.postgresql.auth.username }}; do
                sleep 2
              done
              echo "Waiting for PostGIS extension to exist..."
              until psql "host=$POSTGRES_HOST port=$POSTGRES_PORT dbname=$POSTGRES_DATABASE user=$POSTGRES_USER password=$POSTGRES_PASSWORD" -tAc "SELECT 1 FROM pg_extension WHERE extname = 'postgis'" | grep -q 1; do
                sleep 2
              done
          securityContext:
            runAsUser: 1000
            {{- toYaml .Values.containerSecurityContext | nindent 12 }}
          env: {{ include "mychart.postgresEnv" . | nindent 12 }}
          resources:
            limits:
              memory: 32Mi
      containers:
        - name: api
          image: "{{ .Values.api.image.repository }}:{{ .Values.api.image.tag }}"
          imagePullPolicy: {{ .Values.api.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.api.port }}
          env:
            - name: DJANGO_SECRET_KEY
              value: dev-secret-key-change-me
            - name: DJANGO_DEBUG
              value: "1"
            - name: DJANGO_ALLOWED_HOSTS
              value: localhost,127.0.0.1,0.0.0.0,{{ .Values.ingress.host }}
            - name: APP_ROOT_PATH
              value: {{ .Values.ingress.api.path }}
            {{ include "mychart.postgresEnv" . | nindent 12 }}
          command:
            - sh
            - -c
            - |
              python manage.py migrate &&
              poetry run gunicorn config.wsgi:application -w {{ .Values.api.workers }} -b 0.0.0.0:{{ .Values.api.port }} --timeout {{ .Values.api.timeout }}
          securityContext:
            runAsUser: 1000
            {{- toYaml .Values.containerSecurityContext | nindent 12 }}
          resources:
            limits:
              memory: 256Mi
      imagePullSecrets:
        - name: ghcr-pull-login
