apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "paidiver-annotations-api.fullname" . }}
  labels:
    {{- include "paidiver-annotations-api.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
      component: {{ .Values.api.componentName }}
      {{- include "paidiver-annotations-api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
        component: {{ .Values.api.componentName }}
        {{- include "paidiver-annotations-api.labels" . | nindent 8 }}
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        - name: wait-for-postgres
          image: bitnami/postgresql:latest
          command:
            - sh
            - -ec
            - |
              echo "Waiting for PostgreSQL..."
              until pg_isready \
                -h $POSTGRES_HOST \
                -p $POSTGRES_PORT \
                -U $POSTGRES_USER; do
                sleep 2
              done
              echo "Waiting for PostGIS extension to exist..."
              until psql "host=$POSTGRES_HOST port=$POSTGRES_PORT dbname=$POSTGRES_DATABASE user=$POSTGRES_USER password=$POSTGRES_PASSWORD" -tAc "SELECT 1 FROM pg_extension WHERE extname = 'postgis'" | grep -q 1; do
                sleep 2
              done
          securityContext:
            {{- toYaml .Values.api.initContainer.securityContext | nindent 12 }}
            {{- toYaml .Values.containerSecurityContext | nindent 12 }}
          env: {{ include "api.postgresEnv" . | nindent 12 }}
      containers:
        - name: api
          image: "{{ .Values.api.image.repository }}:{{ .Values.api.image.tag }}"
          imagePullPolicy: {{ .Values.api.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.api.port }}
          env:
            - name: DJANGO_SECRET_KEY
              value: {{ .Values.api.env.djangoSecretKey }}
            - name: DJANGO_DEBUG
              value: "{{ .Values.api.env.djangoDebug }}"
            - name: DJANGO_ALLOWED_HOSTS
              value: localhost,127.0.0.1,0.0.0.0,{{ .Values.ingress.host }}
            {{ include "api.postgresEnv" . | nindent 12 }}
          command:
            - sh
            - -c
            - |
              python manage.py migrate &&
              poetry run gunicorn config.wsgi:application -w {{ .Values.api.workers }} -b 0.0.0.0:{{ .Values.api.port }} --timeout {{ .Values.api.timeout }}
          securityContext:
            {{- toYaml .Values.api.securityContext | nindent 12 }}
            {{- toYaml .Values.containerSecurityContext | nindent 12 }}
      imagePullSecrets:
        - name: {{ .Values.api.image.imagePullSecret }}
