apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "{{ .Release.Name }}-ingress"
spec:
  ingressClassName: {{ .Values.ingress.ingressClassName }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: "/{{ .Values.ingress.api.path }}"
            pathType: Prefix
            backend:
              service:
                name: "{{ .Release.Name }}-{{ .Values.api.componentName }}-service"
                port:
                  number: {{ .Values.api.service.port }}
