apiVersion: v2
name: api
description: A database and API for imagery metadata and annotations
type: application
version: 0.0.0-dev
appVersion: 0.0.0-dev
maintainers:
  - name: eawetchy
    email: elisabeth.wetchy@noc.ac.uk
    url: bodc.ac.uk

dependencies:
  - name: postgresql
    version: 18.2.4
    repository: https://charts.bitnami.com/bitnami
